services:
  mysql:
    image: mysql:8.0
    container_name: mysql-petclinic
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_USERNAME: root
      MYSQL_DATABASE: petclinic
    ports:
      - "3309:3306"
    networks:
      - petclinic-network

  spring-petclinic-api-gateway:
    build:
      context: ../.
      args: 
        FOLDER: ./spring-petclinic-api-gateway
      dockerfile: ./docker/Dockerfile
    container_name: spring-petclinic-api-gateway
    ports:
      - "8080:8080"
    environment:
      - app.customers.uri=http://spring-petclinic-customers-service:8082
      - app.vets.uri=http://spring-petclinic-vets-service:8083
      - app.visits.uri=http://spring-petclinic-visits-service:8084
    depends_on:
      - mysql
      - spring-petclinic-customers-service
      - spring-petclinic-vets-service
      - spring-petclinic-visits-service

  spring-petclinic-customers-service:
    build:
      context: ../.
      args: 
        FOLDER: ./spring-petclinic-customers-service
      dockerfile: ./docker/Dockerfile
    container_name: spring-petclinic-customers-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - petclinic-network

  spring-petclinic-vets-service:
    build:
      context: ../.
      args: 
        FOLDER: ./spring-petclinic-vets-service
      dockerfile: ./docker/Dockerfile
    container_name: spring-petclinic-vets-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - petclinic-network

  spring-petclinic-visits-service:
    build:
      context: ../.
      args: 
        FOLDER: ./spring-petclinic-visits-service
      dockerfile: ./docker/Dockerfile
    container_name: spring-petclinic-visits-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql
    networks:
      - petclinic-network
    
networks:
  petclinic-network:
    driver: bridge
 