apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-ui
  name: vote-ui
spec:
  type: NodePort
  ports:
    - name: "vote-ui-service"
      port: 5001
      targetPort: 80
      nodePort: 30001
  selector:
    app: vote-ui
