apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}  
  containers:
    - name: writer
      image: busybox
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/data
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            echo "<html><body><h1>$(date)</h1><p>Hello c'est pas dur</p></body></html>" > /usr/share/data/index.html
            sleep 5
          done
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html